@TestOn('vm')
library test.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test -e Environment.vm --no-genHtml`

import './unit/executable_test.dart' as unit_executable_test;
import './unit/src/utils_test.dart' as unit_src_utils_test;
import 'package:test/test.dart';

void main() {
  unit_executable_test.main();
  unit_src_utils_test.main();
}
